import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'language': 'Language',
          'select_language': 'Select language',
          'home': 'Home',
          'e-Wallet': 'E-Wallet',
          'history': 'History',
          'schedule': 'Schedule',
          'notification': 'Notification',
          'help_center': 'Help Center',
          'setting': 'Setting',
          'emergency_contacts': 'Emergency Contacts',
          'package_history': 'Package History',
          'subscription': 'Subscription',
          'cash_out': 'Cash Out',
          'logout': 'Logout',
          'vehicle_management': 'Vehicle Management',
          'document_management': 'Document Management',
          'term_conditions': 'Term & Conditions',
          'privacy_policy': 'Privacy Policy',
          'contact_us': 'Contact Us',
          'add_balance': 'Add Balance',
          'select_a_top-up_value': 'Select a top up value',
          'pay': 'Pay',
          'add': 'Add',
          'you_balance': 'You Balance',
          'id': 'ID',
          'vehicle_category': 'Vehicle Category',
          'total_distance': 'Total Distance',
          'total_fare': 'Total Fare',
          'payment_type': 'Payment Type',
          'payable_amount': 'Payable Amount',
          'vehicle_number': 'Vehicle Number',
          'distance': 'Distance',
          'trip_details': 'Trip Details',
          'favorite_places': 'Favorite Places',
          'add_home': 'Add Home',
          'add_work': 'Add Work',
          'saved_places': 'Saved Places',
          'more_places': 'More Places',
          'add_new': 'Add New',
          'recently_visited_places': 'Recently Visited Places',
          'tap_to_select_from_the_map': 'Tap to select from the map',
          'cash': 'Cash',
          'promo': 'Promo',
          'option': 'Option',
          'payment_option': 'Payment Option',
          'e-wallet_balance': 'E-Wall Balance',
          'credit_card': 'Credit Card',
          'rate_us': 'Rate Us',
          'submit': 'Submit',
          'your_feedback': 'Your feedback',
          'enter_code_promo': 'Enter Code Promo',
          'add_promo_code': 'Add Promo Code',
          "today's_earned": "Today's Earned: ",
          'login': 'Login',
          'register': 'Register',
          'phone_number': 'Phone Number',
          'personal_verification': 'Personal Verification',
          'dec_register':
              'Please upload required documents. Get verified to start Riding',
          'first_name': 'First Name',
          'last_name': 'Last Name',
          'your_email': 'Your Email',
          'accept': 'Accept',
          'decline': 'Decline',
          'goto_pickup': 'Go to Pickup',
          'minimum_fare': 'Minimum Fare',
          'confirm_total': 'Confirm​Total',
          'total_earned': 'Total Earned',
          'weekly': 'Weekly',
          'daily': 'Daily',
          'start_trip': 'Start Trip',
          'remaining_cash_out_amount': 'Remaining Cash Out Amount',
          'transfer_request': 'Transfer Request',
          'transfer_process':
              'This amount will be transferred to your bank account within 10 working days.',
          'enter_amount': 'Enter Amount',
          'note': 'Note: Please note that there will be a \$1 charge',
          'cash_out_history': 'Cash Out History',
          'add_vehicle': 'Add Vehicle',
          'vehicle_detail': 'Vehicle Detail',
          'dec_vehicle_detail':
              'Please upload required documents.Get verified to start Start Driving',
          'select_vehicle_types': 'Select Vehicle Types',
          'brand_model': 'Brand & Model',
        },
        ''
            'kh': {
          'language': 'ភាសា',
          'select_language': 'ជ្រើសរើសភាសា',
          'home': 'ទំព័រដើម',
          'e-Wallet': 'កាបូបលុយ',
          'history': 'ប្រវិត្តិប្រតិបត្តិការណ៍',
          'schedule': 'កាលវិភាគ',
          'notification': 'ដំណឹង',
          'help_center': 'ជំនួយ',
          'setting': 'ការកំណត់',
          'emergency_contacts': 'ទំនាក់ទំនងបន្ទាន់',
          'package_history': 'ប្រវត្តិ',
          'subscription': 'ការជាវ',
          'cash_out': 'ប្រាក់ចំណាយ',
          'logout': 'ចាកចេញ',
          'vehicle_management': 'ការគ្រប់គ្រងយានយន្ត',
          'document_management': 'ការគ្រប់គ្រងឯកសារ',
          'term_conditions': 'ល័ក្ខខ័ណ្ឌ',
          'privacy_policy': 'គោលការណ៍​ភាព​ឯកជន',
          'contact_us': 'ទំនាក់ទំនង',
          'add_balance': 'បន្ថែមទឹកប្រាក់',
          'select_a_top-up_value': 'ជ្រើសរើសចំនួនទឹកប្រាក់',
          'pay': 'បញ្ចូលប្រាក់',
          'add': 'បន្ថែម',
          'you_balance': 'ទឹកប្រាក់របស់អ្នក',
          'id': 'លេខសំគាល់',
          'vehicle_category': 'ប្រភេទរថយន្ត',
          'total_distance': 'ចំងាយសរុប',
          'total_fare': 'ថ្លៃសរុប',
          'payment_type': 'ប្រភេទបង់ប្រាក់',
          'payable_amount': 'ចំនួនទឹកប្រាក់ដែលត្រូវបង់',
          'vehicle_number': 'លេខសំគាល់រថយន្ដ',
          'distance': 'ចំងាយ',
          'time': 'រយៈពេល',
          'price': 'តម្លៃ',
          'trip_details': 'ព័ត៌មានលម្អិតការធ្វើដំណើរ',
          'saved_places': 'កំណត់ទីកន្លែង',
          'favorite_places': 'ទីកន្លែងដែលចូលចិត្ត',
          'add_home': 'បន្ថែមអាសយដ្ឋានផ្ទះ',
          'add_work': 'បន្ថែមអាស័យដ្ឋានការងារ',
          'more_places': 'ទីតាំងផ្សេងទៀត',
          'add_new': 'បន្ថែមទីតាំងថ្មី',
          'recently_visited_places': 'កន្លែងដែលធ្លាប់ធ្វើដំណើរ',
          'tap_to_select_from_the_map': 'កំណត់ទីតាំងនៅលើផែនទី',
          'cash': 'សាច់ប្រាក់',
          'promo': 'កូដប្រូម៉ូសិន',
          'option': 'ជម្រើសផ្សេងៗ',
          'book': 'កក់ឥឡូវនេះ',
          'payment_option': 'ជម្រើសបង់ប្រាក់',
          'e-wallet_balance': 'ទឹកប្រាក់ក្នុងកាបួប',
          'credit_card': 'កាត',
          'rate_us': 'ការវាយតម្លៃ',
          'submit': 'ដាក់បញ្ចូល',
          'your_feedback': 'យោបល់របស់អ្នក',
          'enter_code_promo': 'បញ្ចូលកូដប្រូម៉ូសិន',
          'add_promo_code': 'កូដប្រូម៉ូសិន',
          "today's_earned": 'ចំណូលថ្ងៃនេះ',
          'login': 'ចូល',
          'register': 'ចុះឈ្មោះ',
          'phone_number': 'លេខទូរស័ព្ទ',
          'personal_verification': 'ព័តមានផ្ទាល់ខ្លួន',
          'dec_register': 'សូមបំពេញព័តមានខាងក្រោម ដើម្បីចាប់ផ្ដើមប្រើប្រាស់',
          'first_name': 'នាមខ្លួន',
          'last_name': 'នាមត្រកូល',
          'your_email': 'អ៊ីម៉ែល',
          'accept': 'ទទួល',
          'decline': 'មិនទទួល',
          'goto_pickup': 'ទីតាំងទទួលយក',
          'minimum_fare': 'ថ្លៃអប្បបរមា',
          'confirm_total': 'យល់ព្រម',
          'total_earned': 'ប្រាក់រកបានសរុប',
          'weekly': 'ប្រចាំសប្តាហ៍',
          'daily': 'ប្រចាំថ្ងៃ',
          'start_trip': 'ការធ្វើដំណើរចាប់ផ្តើម',
          'remaining_cash_out_amount': 'ចំនួនសាច់ប្រាក់នៅសល់',
          'transfer_request': 'ការផ្ទេរទឹកប្រាក់',
          'transfer_process':
              'ចំនួនទឹកប្រាក់នេះនឹងត្រូវផ្ទេរទៅគណនីធនាគាររបស់អ្នកក្នុងរយៈពេល ១០ ក្នុងថ្ងៃធ្វើការ។',
          'enter_amount': 'បញ្ចូលចំនួនទឹកប្រាក់',
          'note': 'សម្គាល់ៈ គិតប្រាក់ ១ ដុល្លារ សំរាប់សេវាកម្ម',
          'cash_out_history': 'ប្រាក់ចំណាយពីមុន',
          'add_vehicle': 'អំពីរថយន្ដ',
          'vehicle_detail': 'ព័តមានអំពីរថយន្ដ',
          'dec_vehicle_detail':
              'សូមបំពេញព័តមានអំពីរថយន្ដ ដើម្បីចាប់ផ្ដើមប្រើប្រាស់',
          'select_vehicle_types': 'ជ្រើសរើសប្រភេទរថយន្ដ',
          'brand_model': 'ម៉ូដែលរថយន្ដ',
        },
      };
}
